### ISSUE TITLE
Doesn't copy animation

### ISSUE THREAD

**Issue by kevva** [kevva/kap-clipboard#1] opened 2017-05-30 12:41 UTC
Don't really know why. This might help if someone wants to investigate https://stackoverflow.com/questions/33675297/copy-gif-to-uipasteboard/33690807#33690807.

**Comment by gingerbbm** [comment] 2018-03-19 17:38
I experienced this today.

**Platform: Mac OS X 10.13.3 (17D102)**
**Kap Version: Version 2.0.0 (2.0.0.681)**
### Steps to reproduce
I kapture an area of the screen. Then, under "Export GIF" I choose "Copy to clipboard".
### Expected behaviour
What I expect to happen is that I end up with an animated GIF in my clipboard.
### Current behaviour
What I get is a static PNG in my clipboard.
### Workaround
None.

**Comment by kevva** [comment] 2018-03-21 18:34
There's an issue over at the `electron` repo for it https://github.com/electron/electron/issues/5078.

**Comment by sindresorhus** [comment] 2019-03-28 15:57
The correct way to put an animated GIF in the clipboard is to either:

1. Put a file URL on the clipboard that points to the GIF.
2. Add the GIF as an attachment to a `NSAttributedString` and add it to the pasteboard as type `NSRTFDPboardType`.

We cannot do either, since Electron doesn't support putting a file URL on the clipboard or let us put a RTFD. It does support a RTF (without graphics) however.

Someone will need to open two Electron issues about this, and link back here.

**Comment by sindresorhus** [comment] 2019-08-23 19:26
Fixed by https://github.com/wulkano/kap/commit/ddba6081725f806dc97fb35eb8e326b9ccf823d1. This functionality is now in Kap itself.

**Closed as completed by sindresorhus** 2019-08-23 19:26 UTC
Labels: bug, help wanted

**Comment by CharlesARoy** [comment] 2020-11-12 23:09
@sindresorhus By "This functionality is now in Kap itself" does that mean it's supposed to work now? For me, when I select "Copy to Clipboard" and then paste the gif anywhere, it still doesn't animate.

**Comment by sindresorhus** [comment] 2020-11-13 01:28
@CharlesARoy Yes, but note that it doesn't work to paste it into Chrome and Chrome-based apps because of a long-running Chrome bug.
